/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as DashboardWorkspacesWorkspaceIdRouteImport } from './routes/_dashboard.workspaces.$workspaceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInfrastructureProbeRouteImport } from './routes/api/infrastructure/probe'
import { Route as ApiWorkspacesWorkspaceIdRouteImport } from './routes/api/workspaces/$workspaceId'
import { Route as ApiWorkspacesWorkspaceIdAgentRouteImport } from './routes/api/workspaces/$workspaceId/agent'
import { Route as ApiWorkspacesWorkspaceIdRetryRouteImport } from './routes/api/workspaces/$workspaceId/retry'
import { Route as ApiWorkspacesWorkspaceIdStreamRouteImport } from './routes/api/workspaces/$workspaceId/stream'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesWorkspaceIdRoute =
  DashboardWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfrastructureProbeRoute = ApiInfrastructureProbeRouteImport.update({
  id: '/api/infrastructure/probe',
  path: '/api/infrastructure/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesWorkspaceIdRoute =
  ApiWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ApiWorkspacesRoute,
  } as any)
const ApiWorkspacesWorkspaceIdAgentRoute =
  ApiWorkspacesWorkspaceIdAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => ApiWorkspacesWorkspaceIdRoute,
  } as any)
const ApiWorkspacesWorkspaceIdRetryRoute =
  ApiWorkspacesWorkspaceIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => ApiWorkspacesWorkspaceIdRoute,
  } as any)
const ApiWorkspacesWorkspaceIdStreamRoute =
  ApiWorkspacesWorkspaceIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiWorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/workspaces/$workspaceId': typeof DashboardWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/infrastructure/probe': typeof ApiInfrastructureProbeRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/$workspaceId/agent': typeof ApiWorkspacesWorkspaceIdAgentRoute
  '/api/workspaces/$workspaceId/retry': typeof ApiWorkspacesWorkspaceIdRetryRoute
  '/api/workspaces/$workspaceId/stream': typeof ApiWorkspacesWorkspaceIdStreamRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/workspaces/$workspaceId': typeof DashboardWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/infrastructure/probe': typeof ApiInfrastructureProbeRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/$workspaceId/agent': typeof ApiWorkspacesWorkspaceIdAgentRoute
  '/api/workspaces/$workspaceId/retry': typeof ApiWorkspacesWorkspaceIdRetryRoute
  '/api/workspaces/$workspaceId/stream': typeof ApiWorkspacesWorkspaceIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/workspaces/$workspaceId': typeof DashboardWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/infrastructure/probe': typeof ApiInfrastructureProbeRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/$workspaceId/agent': typeof ApiWorkspacesWorkspaceIdAgentRoute
  '/api/workspaces/$workspaceId/retry': typeof ApiWorkspacesWorkspaceIdRetryRoute
  '/api/workspaces/$workspaceId/stream': typeof ApiWorkspacesWorkspaceIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/api/workspaces'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/infrastructure/probe'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/$workspaceId/agent'
    | '/api/workspaces/$workspaceId/retry'
    | '/api/workspaces/$workspaceId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/api/health'
    | '/api/workspaces'
    | '/'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/infrastructure/probe'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/$workspaceId/agent'
    | '/api/workspaces/$workspaceId/retry'
    | '/api/workspaces/$workspaceId/stream'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/settings'
    | '/api/health'
    | '/api/workspaces'
    | '/_dashboard/'
    | '/_dashboard/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/infrastructure/probe'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/$workspaceId/agent'
    | '/api/workspaces/$workspaceId/retry'
    | '/api/workspaces/$workspaceId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInfrastructureProbeRoute: typeof ApiInfrastructureProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/workspaces/$workspaceId': {
      id: '/_dashboard/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof DashboardWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/infrastructure/probe': {
      id: '/api/infrastructure/probe'
      path: '/api/infrastructure/probe'
      fullPath: '/api/infrastructure/probe'
      preLoaderRoute: typeof ApiInfrastructureProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/$workspaceId': {
      id: '/api/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/api/workspaces/$workspaceId'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/workspaces/$workspaceId/agent': {
      id: '/api/workspaces/$workspaceId/agent'
      path: '/agent'
      fullPath: '/api/workspaces/$workspaceId/agent'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdAgentRouteImport
      parentRoute: typeof ApiWorkspacesWorkspaceIdRoute
    }
    '/api/workspaces/$workspaceId/retry': {
      id: '/api/workspaces/$workspaceId/retry'
      path: '/retry'
      fullPath: '/api/workspaces/$workspaceId/retry'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdRetryRouteImport
      parentRoute: typeof ApiWorkspacesWorkspaceIdRoute
    }
    '/api/workspaces/$workspaceId/stream': {
      id: '/api/workspaces/$workspaceId/stream'
      path: '/stream'
      fullPath: '/api/workspaces/$workspaceId/stream'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdStreamRouteImport
      parentRoute: typeof ApiWorkspacesWorkspaceIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkspacesWorkspaceIdRoute: typeof DashboardWorkspacesWorkspaceIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkspacesWorkspaceIdRoute: DashboardWorkspacesWorkspaceIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiWorkspacesWorkspaceIdRouteChildren {
  ApiWorkspacesWorkspaceIdAgentRoute: typeof ApiWorkspacesWorkspaceIdAgentRoute
  ApiWorkspacesWorkspaceIdRetryRoute: typeof ApiWorkspacesWorkspaceIdRetryRoute
  ApiWorkspacesWorkspaceIdStreamRoute: typeof ApiWorkspacesWorkspaceIdStreamRoute
}

const ApiWorkspacesWorkspaceIdRouteChildren: ApiWorkspacesWorkspaceIdRouteChildren =
  {
    ApiWorkspacesWorkspaceIdAgentRoute: ApiWorkspacesWorkspaceIdAgentRoute,
    ApiWorkspacesWorkspaceIdRetryRoute: ApiWorkspacesWorkspaceIdRetryRoute,
    ApiWorkspacesWorkspaceIdStreamRoute: ApiWorkspacesWorkspaceIdStreamRoute,
  }

const ApiWorkspacesWorkspaceIdRouteWithChildren =
  ApiWorkspacesWorkspaceIdRoute._addFileChildren(
    ApiWorkspacesWorkspaceIdRouteChildren,
  )

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesWorkspaceIdRoute: typeof ApiWorkspacesWorkspaceIdRouteWithChildren
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesWorkspaceIdRoute: ApiWorkspacesWorkspaceIdRouteWithChildren,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInfrastructureProbeRoute: ApiInfrastructureProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
