/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiWorkspacesRouteImport } from './routes/api/workspaces'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInfrastructureProbeRouteImport } from './routes/api/infrastructure/probe'
import { Route as ApiWorkspacesWorkspaceIdRouteImport } from './routes/api/workspaces/$workspaceId'
import { Route as ApiWorkspacesWorkspaceIdRetryRouteImport } from './routes/api/workspaces/$workspaceId/retry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesRoute = ApiWorkspacesRouteImport.update({
  id: '/api/workspaces',
  path: '/api/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfrastructureProbeRoute = ApiInfrastructureProbeRouteImport.update({
  id: '/api/infrastructure/probe',
  path: '/api/infrastructure/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspacesWorkspaceIdRoute =
  ApiWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => ApiWorkspacesRoute,
  } as any)
const ApiWorkspacesWorkspaceIdRetryRoute =
  ApiWorkspacesWorkspaceIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => ApiWorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/infrastructure/probe': typeof ApiInfrastructureProbeRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/$workspaceId/retry': typeof ApiWorkspacesWorkspaceIdRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/infrastructure/probe': typeof ApiInfrastructureProbeRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/$workspaceId/retry': typeof ApiWorkspacesWorkspaceIdRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workspaces': typeof ApiWorkspacesRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/infrastructure/probe': typeof ApiInfrastructureProbeRoute
  '/api/workspaces/$workspaceId': typeof ApiWorkspacesWorkspaceIdRouteWithChildren
  '/api/workspaces/$workspaceId/retry': typeof ApiWorkspacesWorkspaceIdRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/workspaces'
    | '/api/auth/$'
    | '/api/infrastructure/probe'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/$workspaceId/retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/workspaces'
    | '/api/auth/$'
    | '/api/infrastructure/probe'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/$workspaceId/retry'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/health'
    | '/api/workspaces'
    | '/api/auth/$'
    | '/api/infrastructure/probe'
    | '/api/workspaces/$workspaceId'
    | '/api/workspaces/$workspaceId/retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWorkspacesRoute: typeof ApiWorkspacesRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInfrastructureProbeRoute: typeof ApiInfrastructureProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces': {
      id: '/api/workspaces'
      path: '/api/workspaces'
      fullPath: '/api/workspaces'
      preLoaderRoute: typeof ApiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/infrastructure/probe': {
      id: '/api/infrastructure/probe'
      path: '/api/infrastructure/probe'
      fullPath: '/api/infrastructure/probe'
      preLoaderRoute: typeof ApiInfrastructureProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspaces/$workspaceId': {
      id: '/api/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/api/workspaces/$workspaceId'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ApiWorkspacesRoute
    }
    '/api/workspaces/$workspaceId/retry': {
      id: '/api/workspaces/$workspaceId/retry'
      path: '/retry'
      fullPath: '/api/workspaces/$workspaceId/retry'
      preLoaderRoute: typeof ApiWorkspacesWorkspaceIdRetryRouteImport
      parentRoute: typeof ApiWorkspacesWorkspaceIdRoute
    }
  }
}

interface ApiWorkspacesWorkspaceIdRouteChildren {
  ApiWorkspacesWorkspaceIdRetryRoute: typeof ApiWorkspacesWorkspaceIdRetryRoute
}

const ApiWorkspacesWorkspaceIdRouteChildren: ApiWorkspacesWorkspaceIdRouteChildren =
  {
    ApiWorkspacesWorkspaceIdRetryRoute: ApiWorkspacesWorkspaceIdRetryRoute,
  }

const ApiWorkspacesWorkspaceIdRouteWithChildren =
  ApiWorkspacesWorkspaceIdRoute._addFileChildren(
    ApiWorkspacesWorkspaceIdRouteChildren,
  )

interface ApiWorkspacesRouteChildren {
  ApiWorkspacesWorkspaceIdRoute: typeof ApiWorkspacesWorkspaceIdRouteWithChildren
}

const ApiWorkspacesRouteChildren: ApiWorkspacesRouteChildren = {
  ApiWorkspacesWorkspaceIdRoute: ApiWorkspacesWorkspaceIdRouteWithChildren,
}

const ApiWorkspacesRouteWithChildren = ApiWorkspacesRoute._addFileChildren(
  ApiWorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWorkspacesRoute: ApiWorkspacesRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInfrastructureProbeRoute: ApiInfrastructureProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
